import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * 🗃️ Data export module
 * Id: 349e975e-6b47-4faf-8020-e234cc600f89
 * Codename: _data_export_module
 */
export type __DataExportModule = IContentItem<{
    /**
     * Export data (custom)
     * Required: false
     * Id: 16589305-3f32-4a34-a231-f07f51d50781
     * Codename: export_data
     */
    exportData: Elements.CustomElement;
}>;
