import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * New content type
 * Id: b5a6f10b-83dd-43cd-81a4-90168ede7292
 * Codename: new_content_type
 */
export type NewContentType = IContentItem<{
    /**
     * Title (text)
     * Required: false
     * Id: b93ec202-0921-4496-943d-a3f815dc54b0
     * Codename: title
     */
    title: Elements.TextElement;
}>;
