import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Person } from './person';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Team Section
 * Id: 6e41e5a9-8d6d-42b9-b810-18c89cb7efde
 * Codename: team_section
 */
export type TeamSection = IContentItem<{
    /**
     * Description (rich_text)
     * Required: false
     * Id: 74cd4131-5482-474b-94ec-8890451262f9
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Team members (modular_content)
     * Required: false
     * Id: 0402cb26-34ab-4b71-af80-e12b7a5ced89
     * Codename: team_members
     */
    teamMembers: Elements.LinkedItemsElement<Person>;

    /**
     * Title (text)
     * Required: false
     * Id: aa9960fe-6dfd-4b57-beab-9d8f691927ad
     * Codename: title
     */
    title: Elements.TextElement;
}>;
