/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Personas
 * Id: 17da24e0-6f89-43c8-9ae5-e52694de1a08
 * Codename: personas
 */
export type Personas =
    | 'the_budget_conscious_buyer'
    | 'the_eco_conscious_innovator'
    | 'the_industry_expert'
    | 'the_practical_professional'
    | 'the_trendsetter';
