/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const webhooks = {
    /**
     * Automatic Translation
     */
    automaticTranslation: {
        url: 'https://idm.kontent.dev/api/translate-webhook/',
        id: 'e7e4cf29-8cc9-4b08-b357-ec1c1ce4342c',
        name: 'Automatic Translation'
    }
} as const;
